# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|

    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt update

    # 安装组件
    apt install tree
    apt install -y gnuplot

    # 安装 ns-3.27 的必须库
    apt install -y gcc g++ python python-dev mercurial bzr gdb valgrind gsl-bin libgsl0-dev flex bison tcpdump sqlite sqlite3 libsqlite3-dev libxml2 libxml2-dev libgtk2.0-0 libgtk2.0-dev uncrustify doxygen graphviz imagemagick texlive texlive-latex-extra texlive-generic-extra texlive-generic-recommended texinfo dia texlive texlive-latex-extra texlive-extra-utils texlive-generic-recommended texi2html python-pygraphviz python-kiwi python-pygoocanvas libgoocanvas-dev python-pygccxml
    cd
    mkdir /home/vagrant/ns3
    cd /home/vagrant/ns3/
    wget https://www.nsnam.org/release/ns-allinone-3.27.tar.bz2
    tar xjf ns-allinone-3.27.tar.bz2
    cd ns-allinone-3.27/
    ./build.py --enable-examples --enable-tests
    cd ns-3.27/
    ./waf -d debug --enable-examples --enable-tests configure
    ./waf
    #./test.py
    cd

    # 从Github 仓库中下载文件.
    # 删除当前的 /home/vagrant/temp 文件夹
    # 防止在reload --provision的时候出错
    rm -r /home/vagrant/tmp
    git clone https://github.com/ituring/tcp-book.git /home/vagrant/tmp/

    # 复制python脚本, shell脚本, scratch目录到ns-3根目录
    cp /home/vagrant/tmp/ns3/*.py /home/vagrant/ns3/ns-allinone-3.27/ns-3.27/
    cp /home/vagrant/tmp/ns3/*.sh /home/vagrant/ns3/ns-allinone-3.27/ns-3.27/
    cp /home/vagrant/tmp/ns3/scratch/* /home/vagrant/ns3/ns-allinone-3.27/ns-3.27/scratch/
    cp -r /home/vagrant/tmp/ns3/data /home/vagrant/ns3/ns-allinone-3.27/ns-3.27/
    cp /home/vagrant/tmp/ns3/requirements.txt /home/vagrant/ns3/ns-allinone-3.27/ns-3.27/
    cp /home/vagrant/tmp/ns3/src/internet/model/* /home/vagrant/ns3/ns-allinone-3.27/ns-3.27/src/internet/model/
    cp /home/vagrant/tmp/ns3/src/internet/test/* /home/vagrant/ns3/ns-allinone-3.27/ns-3.27/src/internet/test/
    cp /home/vagrant/tmp/ns3/src/internet/wscript /home/vagrant/ns3/ns-allinone-3.27/ns-3.27/src/internet/wscript

    cd /home/vagrant/ns3/ns-allinone-3.27/ns-3.27
    chmod -R 777 *

    # 更新 waf 配置
    ./waf clean
    ./waf

    shopt -s dotglob
    chmod -R 777 *
    shopt -u dotglob

    # 安装python库
    apt install python3-pip python3-dev -y
    pip3 install -r requirements.txt

  SHELL

  # 与宿主OS 分享共享文件夹内容
  config.vm.synced_folder './shared', '/home/vagrant/ns3/ns-allinone-3.27/ns-3.27/data', create: true, owner: 'vagrant', group: 'vagrant'

end
